accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from .views import signup

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', signup, name='signup')
]

black/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index' ),
    url(r'^(?P<pk>\d+)/$', views.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/post/$', views.post, name='post'),
    url(r'^(?P<person_pk>\d+)/post/(?P<post_pk>\d+)/$', views.post_detail, name='post_detail')

]

cafe/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from index.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^heuk/', include('black.urls', namespace='black')),
    url(r'^$', home, name='index')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

black/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.

class People(models.Model):
    name=models.CharField(max_length=20)



def upload_location(instance, filename):
    return "%s/%s" %(instance.person.name, filename)

class Post(models.Model):
    title=models.CharField(max_length=30)
    media=models.FileField(upload_to=upload_location, null=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content=models.TextField()
    person=models.ForeignKey(People, default=1)
    writer=models.ForeignKey(settings.AUTH_USER_MODEL, default=1)

class Comment(models.Model):
    post=models.ForeignKey(Post)
    content=models.TextField()
    writer=models.ForeignKey(settings.AUTH_USER_MODEL)

class Like(models.Model):
    post=models.ForeignKey(Post)
    rating=models.DecimalField(max_digits=2, decimal_places=0, validators=[MinValueValidator(0), MaxValueValidator(10)], help_text='10점 만점, 높을수록 극혐!', blank=True, default=5)
    liker=models.ForeignKey(settings.AUTH_USER_MODEL, default=1)

index/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    first_name=forms.CharField(max_length=10)

    def save(self, commit=True):
        user=super(SignupForm, self).save(commit=False)
        user.first_name=self.cleaned_data['name']

        if commit:
            user.save()
        return user

    class Meta:
        model=User
        fields=['username', 'password1', 'password2', 'first_name']

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = '아이디를 입력하세요.'
        self.fields['password1'].label = '비밀번호를 입력하세요.'
        self.fields['password2'].label = '비밀번호를 다시 한 번 입력하세요.'
        self.fields['first_name'].label = '이름을 적어주세요.'

    def clean_name(self):
        data=self.cleaned_data['first_name']
        if User.objects.filter(first_name=data).exists():
            raise forms.ValidationError('이미 회원가입이 완료되었습니다.')
        return data

black/forms.py
from django import forms
from django.forms import ModelForm, NumberInput
from .models import Post, Comment, Like


class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title', 'media', 'content']
        labels={'title':'제목', 'media':'극혐자료', 'content':'내용'}

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content']
        labels={'content':'답글'}

class LikeForm(forms.ModelForm):
    class Meta:
        model=Like
        fields=['rating']
        labels={'rating':'극혐 정도'}

accounts/views.py
from django.shortcuts import render
from .forms import SignupForm

# Create your views here.

def signup(request):
    if request.method=='POST':
        s=SignupForm(request.POST)
        if s.is_valid():
            s.save()
            return redirect('login')
    else:s=SignupForm()

    return render(request, 'accounts/signup.html', {'form':s})

black/views.py
from django.shortcuts import render, redirect
from .models import People, Like, Post, Comment
from .forms import PostForm, CommentForm, LikeForm
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
# Create your views here.
def index(request):
    people_list=People.objects.all()
    return render(request, 'black/index.html', {'people_list':people_list})

def post(request, pk):
    instance=People.objects.get(pk=pk)
    if request.method=='POST':
        p=PostForm(request.POST, request.FILES)
        if p.is_valid():
            new_post=p.save(commit=False)
            new_post.writer=request.user
            new_post.person=instance
            new_post.save()

            return redirect('black:post_detail', person_pk=instance.pk, post_pk=new_post.pk)
    else:
        p=PostForm()

    return render(request, 'black/post.html', {'form':p})

def post_detail(request, person_pk, post_pk):
    instance=People.objects.get(pk=person_pk)
    post=Post.objects.get(pk=post_pk)
    comments=Comment.objects.filter(post=post_pk)
    likes=Like.objects.filter(post=post_pk)
    num_likes=Like.objects.filter(post=post_pk).count()
    avg=Like.objects.filter(post=post_pk).aggregate(Avg('rating')).values()
    likes_avg=list(avg)[0]


    if request.method=='POST':
        if request.POST['form_type'] == u'like':
            l=LikeForm(request.POST,)

            if l.is_valid():
                new_like=l.save(commit=False)
                new_like.writer=request.user
                new_like.post=post
                new_like.save()

                return redirect('black:post_detail', person_pk=instance.pk, post_pk=post.pk)



        else:
            c=CommentForm(request.POST,)

            if c.is_valid():
                new_comment=c.save(commit=False)
                new_comment.writer=request.user
                new_comment.post=post
                new_comment.save()

                return redirect('black:post_detail', person_pk=instance.pk, post_pk=post.pk)

    else:
        l=LikeForm()
        c=CommentForm()

    context={'post':post, 'comments':comments, 'likes':likes, 'num_likes':num_likes, 'commentform': c, 'likeform': l, 'avg':likes_avg}
    return render(request, 'black/post_detail.html', context)


def post_list(request, pk):
    instance=People.objects.get(pk=pk)
    post_list=Post.objects.filter(person=pk)
    return render(request, 'black/post_list.html', {'person': instance ,'post_list':post_list})

index/views.py
from django.shortcuts import render, redirect
from black.models import People

# Create your views here.

def home(request):

    return render(request, 'index/home.html')

accounts/templates/accounts/signup.html
{% load bootstrap3 %}
<form action="" method="post">
{% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" value="회원가입">
</form>

black/templates/black/index.html
{% extends 'index/base.html' %}
{% load staticfiles %}
{% block content %}

<hr>
<section id="services" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">문과의 얼굴들</h2>
                    <h3 class="section-subheading text-muted">스누웨이는 서울대학교 벤처경영학과에서 진행하는 프로젝트입니다. <br>웹사이트는 연합동아리 '피로그래밍'를 통해 제작되었습니다.</h3>
                </div>
            </div>

            <div class="row">
            {% for person in people_list %}
                <div class="col-sm-4">

                    <div class="team-member">
                    <a href="{% url 'black:post_list' person.pk %}">
                        <img src="\static\img\logo_snuway.png" class="img-responsive img-circle" alt="logo_snuway">
                        <h4>{{person.name}}</a></h4>
                        <p class="text-muted">서울대학교 벤처경영학과 프로젝트</p>

<!--                         <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul> -->
                    </div>

                </div>
                {% endfor %}
                </div>
                </div>

{% endblock%}

black/templates/black/post.html
{% load bootstrap3 %}

<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_form form%}
    <input type="submit" value="작성완료">
</form>

black/templates/black/post_detail.html
{% extends 'index/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block content%}
<hr>
<section id="services">
<div class="container">
<div class="row">
<div class="col-lg-12">

<h2 class="section-heading">{{post.title}}</h2>
<hr><br>
<h3>{{post.content}}</h3>
<br>
<p><img src="{{post.media.url}}" style="width: 50%;" ></p>
<hr>
<p>따봉 수 : {{num_likes}}</p>
<p>평균 극혐 지수 : <font color='#fed136' size='5'>{{avg|floatformat:1}}</font></p>
따봉한 사람 :
{% for like in likes %}
{{like.liker}}
{% endfor %}
<hr>

<div>
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form likeform %}
    <input type="hidden" name="form_type" value="like">
    <input type="submit" value="극혐!" name="like">
</form>
<hr>
</div>
{% for comment in comments %}
{{comment.content}}
{% endfor %}
<div>
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form commentform %}
    <input type="hidden" name="form_type" value="comment">
    <input type="submit" value="답글 달기">
</form>
</div>
</div>
</section>
{% endblock %}

black/templates/black/post_list.html
{% extends 'index/base.html' %}
{% load staticfiles %}
{% block content %}
<hr>
<section id="services">
<div class="container">
<div class="col-lg-12 text-center">
                    <h2 class="section-heading">전민규</h2>
                    <h3 class="section-subheading text-muted">내 친구의 가장 개같은 순간들, 모두 공유하세요</h3>
                </div>
            </div>
{% for post in post_list %}
<div class="row">
<div class='col-sm-4'>
<div class="team-member">
<a href="{% url 'black:post_detail' person.pk post.pk %}">
<img src= {{post.media.url}} class="img-responsive" alt="{{post.person}}">

            <p><h5>{{post.title}}</h5></p>{{post.writer.name}}({{post.writer}})</a>
            </div>

            </div>

        {% endfor %}
        </div>
<div class='row'>
<div class='col-sm-4'>
<a type="button" href="{% url 'black:post' person.pk %}" class="btn btn-primary">새 글 쓰기</a>
</div>
</div>

</section>
{% endblock %}

index/templates/index/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>스누웨이</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <!-- Theme CSS -->
    <link href="{% static 'css/agency.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<div id="page-top" class="index">

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> 메뉴 <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">반포고 커뮤니티</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">흑역사 박물관</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">개발자 소개</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li>
                        <a class="page-scroll" href="#">마이페이지</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url "logout" %}?next={{ request.path }}">로그아웃</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="page-scroll" href="{% url "login" %}?next={{ request.path }}">로그인</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url "signup" %}">회원가입</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    </div>
    {% block content %}
    {% endblock %}

    <!-- 로그인 모달
        <div class="modal fade" id="login">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">x</button>
                        <h4 class="modal-title">로그인</h4>
                        <span class="text-muted">아이디와 비밀번호를 입력해주세요.</span>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="아이디(이메일) *" id="email" required data-validation-required-message="아이디(이메일)을 입력해주세요.">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="비밀번호 *" id="password" required data-validation-required-message="비밀번호를 입력해주세요."></input>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <button type="submit" class="btn btn-default">로그인</button>
                                <button type="submit" class="btn btn-default">아이디/비밀번호 찾기</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     로그인 모달 끝 -->

    <footer>
        <div class="container1">
            <div class="row">
                <div class="col-md-3">
                    <span class="copyright">Copyright &copy; 전민규(JMK) 2016</span>
                </div>
                <div class="col-md-4">
                    <button class="page-scroll btn btn-default" data-target="#contact" data-toggle="modal">문의하기</button>
                    <div class="modal fade" id="contact">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">x</button>
                                    <h4 class="modal-title">문의하기</h4>
                                    <span class="text-muted">문의 내용은 개발자에게 전달됩니다.</span>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="이름 *" id="name" required data-validation-required-message="이름을 적어주세요.">
                                                <p class="help-block text-danger"></p>
                                            </div>
                                            <div class="form-group">
                                                <input type="email" class="form-control" placeholder="이메일 *" id="email" required data-validation-required-message="이메일을 적어주세요.">
                                                <p class="help-block text-danger"></p>
                                            </div>
                                            <div class="form-group">
                                                <input type="tel" class="form-control" placeholder="휴대폰 번호 *" id="phone" required data-validation-required-message="휴대폰 번호를 적어주세요.">
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <textarea class="form-control" placeholder="메세지 *" id="message" required data-validation-required-message="메세지를 적어주세요."></textarea>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="col-lg-12 text-center">
                                            <div id="success"></div>
                                            <button type="submit" class="btn btn-default">보내기</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">개인정보취급방침</a>
                        </li>
                        <li><a href="#">이용약관</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/agency.min.js' %}"></script>

</body>

</html>

index/templates/index/home.html
{% extends 'index/base.html' %}
{% load staticfiles %}
{% block content %}

<header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">반포고 문과의 잡동사니 공간</div>
                <div class="intro-heading">BANPO</div>




            </div>
        </div>
    </header>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">흑역사 박물관</h2>
                    <h3 class="section-subheading text-muted">내 친구의 가장 개같은 순간들, 모두 공유하세요</h3>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                    <a href="/heuk">
                        <img src="\static\img\icon_segway.png" alt="segway" class="img-responsive">
                    </span>
                    <h4 class="service-heading">찬찬히 구경하기</a></h4>
                    <p class="text-muted">세그웨이, 전동킥보드, 외발휠 등 다양한 종류의 퍼스널 모빌리티를 만나볼 수 있습니다.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <img src="\static\img\icon_calendar.png" alt="calendar" class="img-responsive">
                    </span>
                    <h4 class="service-heading">명예의 전당</h4>
                    <p class="text-muted">원하는 대여 날짜와 시간대를 손쉽게 설정, 관리할 수 있는 달력 기능을 제공합니다.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <img src="\static\img\icon_map.png" alt="map" class="img-responsive">
                    </span>
                    <h4 class="service-heading">새로운 인물 추가하기</h4>
                    <p class="text-muted">빌려주거나 빌릴 위치를 원하는 대로 검색하고 설정할 수 있습니다.  </p>
                </div>
            </div>
        </div>
    </section>

    {% endblock %}